### PR TITLE
Make std::move qualified, which seems to be required by C++20

### PR DESCRIPTION
**Pull request by kylepl**
This fixes the compile errors. Or at least required by Zig's compiler - either way - seems worth upstreaming.

### CODE REVIEW

**Comment by jmccl** [comment]
This doesn't appear necessary with gcc 12 with std=c++20. I'd heard of zig (barely) but didn't know it could compile C++. This link makes it look easy to set up.

https://zig.news/kristoff/compile-a-c-c-project-with-zig-368j

Is it, or am I in for a lot of pain?

**Comment by jmccl** [comment]
Or, perhaps more easily, what's the compile error you're getting?

**Comment by kylepl** [comment]
I'm using Zig via bazel, so it's a bit abstracted away from me, so not quite sure how easy it is to try, though the link you send does say the interface is the same as clang.

I get:

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/acme-lw/lib/acme-lw.cpp:87:16: error: unqualified call to 'std::move' [-Werror,-Wunqualified-std-cast-call]
        ptr_ = move(ptr.ptr_);
```

and I found some discussion about it here: https://www.mail-archive.com/cfe-commits@lists.llvm.org/msg266296.html (e.g. ```
> Well, the original raison d'etre for D119670 was the observation that `using 
> namespace std::views; auto y = move(x);` will change behavior in C++23, if 
> C++23 adds `std::views::move` as a view adaptor. There's nothing in that 
> story that involves a //user-defined// function named `move`; the reason we 
> want to warn people off of unqualified `move` (or unqualified 
> //anything//-in-std) is for SD-8-adjacent reasons: we want the library to be 
> free to add new entities (such as `std::views::move` specifically) without 
> breaking old code. (Note: the above code involves a second red flag — `using 
> namespace` — so we don't expect it to be //common//.)
```

So it seems like given folks on at least some compilers are trying to avoid, seems reasonable to just qualify it.

**Comment by jmccl** [comment]
Thank you for adding this. My initial reaction is the clang change is somewhat silly, but I agree something should be done to address it. Give me a few days to dig in and think about it.

**Comment by jmccl** [comment]
I've put some commits in (I blew it the first time) to address this by changing the compiler flags rather than changing the code. My current assumption is that the warning will be removed, or at least removed from -Wall at some point. If I'm wrong I'll likely revert what I've done and use your patch, but at the moment this seems like it's a poorly thought out clang  change and I'll suppress it rather than giving in to it.

Please let me know if these commits address your use case.

**Comment by kylepl** [comment]
`-Wno-unqualified-std-cast-call` does resolve it for my use case, thanks.

**Pull request closed without merging**
